In [1]:
# import necessary libraries
import os
import pandas as pd
import numpy as np

# ignore DtypeWarning warnings
import warnings
warnings.filterwarnings("ignore")

In [2]:
def filter_dataframe(df, kinase_name):
    df_new = df[df['KINASE_psp'] == kinase_name]
    filtered_df = df_new[df_new['SUB_MOD_RSD_psp'].values == df_new['Phosphosite_johnson'].values]
    return filtered_df

In [3]:
def filter_dataframe2(df, kinase_name):
    df_new = df[df['KINASE_psp'] == kinase_name]
    # filtered_df = df_new[df_new['SUB_MOD_RSD_psp'].values == df_new['Phosphosite_johnson'].values]
    return df_new

In [4]:
def clean_dataframe(df, data):
    df_clean = pd.DataFrame()
    for kinase in df['KINASE_psp'].unique():
        filtered_df = filter_dataframe2(df, kinase)
        df_clean = pd.concat([df_clean, filtered_df])

    # assert sum(df_clean['SUB_MOD_RSD_psp'].values == df_clean['Phosphosite_johnson'].values) == len(df_clean) # check if all phosphosites are the same

    # check if 'SITE_+/-7_AA_psp and 'SITE_+/-7_AA_johnson' are the same , otherwise print that they all are not the same
    # make SITE_+/-7_AA_johnson column all caps 
    df_clean['SITE_+/-7_AA_psp'] = df_clean['SITE_+/-7_AA_psp'].str.upper()
    if not sum(df_clean['SITE_+/-7_AA_psp'].values == df_clean['SITE_+/-7_AA_johnson'].values) == len(df_clean): 
        print(f" For {data} dataset , out of {len(df_clean)} rows, {sum(df_clean['SITE_+/-7_AA_psp'].values == df_clean['SITE_+/-7_AA_johnson'].values)} are the same")
    else:
        print(f"For {data} dataset, all SITE_+/-7_AA_psp and SITE_+/-7_AA_johnson are the same")
    
    return df_clean

In [5]:
filter_dataframe(pd.read_csv('../data/merged_kinase_' + 'ranked_1.csv'), 'HRI')

,Unnamed: 0,KINASE_psp,SUBSTRATE_psp,KIN_ORGANISM_psp,SUB_ORGANISM_psp,SITE_+/-7_AA_psp,SUB_MOD_RSD_psp,KIN_ACC_ID_psp,SUB_GENE_ID_psp,SUB_ACC_ID_psp,SITE_GRP_ID_psp,Uniprot Primary Accession_johnson,Protein_johnson,Phosphosite_johnson,SITE_+/-7_AA_johnson,ranked_1_johnson
0,0,HRI,eIF2-alpha,human,human,MILLsELsRRRIRsI,S52,Q9BQI3,1965.0,P05198,447635.0,P05198,IF2A,S52,MILLSELSRRRIRSI,HRI

In [6]:
filter_dataframe2(pd.read_csv('../data/merged_kinase_' + 'ranked_1.csv'), 'HRI')

,Unnamed: 0,KINASE_psp,SUBSTRATE_psp,KIN_ORGANISM_psp,SUB_ORGANISM_psp,SITE_+/-7_AA_psp,SUB_MOD_RSD_psp,KIN_ACC_ID_psp,SUB_GENE_ID_psp,SUB_ACC_ID_psp,SITE_GRP_ID_psp,Uniprot Primary Accession_johnson,Protein_johnson,Phosphosite_johnson,SITE_+/-7_AA_johnson,ranked_1_johnson
0,0,HRI,eIF2-alpha,human,human,MILLsELsRRRIRsI,S52,Q9BQI3,1965.0,P05198,447635.0,P05198,IF2A,S52,MILLSELSRRRIRSI,HRI
1,1,HRI,eIF2-alpha,human,human,IEGMILLsELsRRRI,S49,Q9BQI3,1965.0,P05198,450210.0,P05198,IF2A,S52,MILLSELSRRRIRSI,HRI

In [7]:
data_list = ['ranked_1.csv', 'ranked_2.csv', 'ranked_3.csv']

In [8]:
for data in data_list:
    df = pd.read_csv('../data/merged_kinase_' + data)
    df_clean = clean_dataframe(df, data)
    df_clean.to_csv('../data/cleaned_' + data, index=False)

 For ranked_1.csv dataset , out of 14284 rows, 394 are the same
 For ranked_2.csv dataset , out of 14143 rows, 330 are the same
 For ranked_3.csv dataset , out of 13995 rows, 275 are the same

In [9]:
filter_dataframe(df, 'HRI')

Empty DataFrame
Columns: [Unnamed: 0, KINASE_psp, SUBSTRATE_psp, KIN_ORGANISM_psp, SUB_ORGANISM_psp, SITE_+/-7_AA_psp, SUB_MOD_RSD_psp, KIN_ACC_ID_psp, SUB_GENE_ID_psp, SUB_ACC_ID_psp, SITE_GRP_ID_psp, Uniprot Primary Accession_johnson, Protein_johnson, Phosphosite_johnson, SITE_+/-7_AA_johnson, ranked_3_johnson]
Index: []

In [10]:
pd.read_csv('../data/cleaned_ranked_1.csv')

,Unnamed: 0,KINASE_psp,SUBSTRATE_psp,KIN_ORGANISM_psp,SUB_ORGANISM_psp,SITE_+/-7_AA_psp,SUB_MOD_RSD_psp,KIN_ACC_ID_psp,SUB_GENE_ID_psp,SUB_ACC_ID_psp,SITE_GRP_ID_psp,Uniprot Primary Accession_johnson,Protein_johnson,Phosphosite_johnson,SITE_+/-7_AA_johnson,ranked_1_johnson
0,0,HRI,eIF2-alpha,human,human,MILLSELSRRRIRSI,S52,Q9BQI3,1965.0,P05198,4.476350e+05,P05198,IF2A,S52,MILLSELSRRRIRSI,HRI
1,1,HRI,eIF2-alpha,human,human,IEGMILLSELSRRRI,S49,Q9BQI3,1965.0,P05198,4.502100e+05,P05198,IF2A,S52,MILLSELSRRRIRSI,HRI
2,2,PKCD,HDAC5,human,human,FPLRKTASEPNLKVR,S259,Q05655,10014.0,Q9UQL6,4.479950e+05,NaN,NaN,NaN,NaN,NaN
3,3,PKCD,PTPRA iso2,human,human,PLLARSPSTNRKYPP,S204,Q05655,5786.0,P18433-2,4.476120e+05,NaN,NaN,NaN,NaN,NaN
4,4,PKCD,PTPRA iso2,human,human,QAGSHSNSFRLSNGR,S180,Q05655,5786.0,P18433-2,1.869334e+09,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14279,14279,ULK2,Raptor,human,human,DTSSLTQSAPASPTN,S859,Q8IYT8,57521.0,Q8N122,2.024885e+06,NaN,NaN,NaN,NaN,NaN
14280,14280,ULK2,DENND3,human,human,ELAPRNSSLRLTDTA,S490,Q8IYT8,22898.0,A2RUS2,2.305019e+07,NaN,NaN,NaN,NaN,NaN
14281,14281,ULK2,DENND3,human,human,THRRMVVSMPNLQDI,S472,Q8IYT8,22898.0,A2RUS2,7.997148e+06,NaN,NaN,NaN,NaN,NaN
14282,14282,ULK2,SEC16A,human,human,LAQPINFSVSLSNSH,S846,Q8IYT8,9919.0,O15027,5.557872e+07,NaN,NaN,NaN,NaN,NaN
14283,14283,ULK2,PIK3C3,human,human,ESSPILTSFELVKVP,S249,Q8IYT8,5289.0,Q8NEB9,3.548321e+07,NaN,NaN,NaN,NaN,NaN

In [11]:
df = pd.read_csv('../data/cleaned_ranked_1.csv')

In [12]:
df

,Unnamed: 0,KINASE_psp,SUBSTRATE_psp,KIN_ORGANISM_psp,SUB_ORGANISM_psp,SITE_+/-7_AA_psp,SUB_MOD_RSD_psp,KIN_ACC_ID_psp,SUB_GENE_ID_psp,SUB_ACC_ID_psp,SITE_GRP_ID_psp,Uniprot Primary Accession_johnson,Protein_johnson,Phosphosite_johnson,SITE_+/-7_AA_johnson,ranked_1_johnson
0,0,HRI,eIF2-alpha,human,human,MILLSELSRRRIRSI,S52,Q9BQI3,1965.0,P05198,4.476350e+05,P05198,IF2A,S52,MILLSELSRRRIRSI,HRI
1,1,HRI,eIF2-alpha,human,human,IEGMILLSELSRRRI,S49,Q9BQI3,1965.0,P05198,4.502100e+05,P05198,IF2A,S52,MILLSELSRRRIRSI,HRI
2,2,PKCD,HDAC5,human,human,FPLRKTASEPNLKVR,S259,Q05655,10014.0,Q9UQL6,4.479950e+05,NaN,NaN,NaN,NaN,NaN
3,3,PKCD,PTPRA iso2,human,human,PLLARSPSTNRKYPP,S204,Q05655,5786.0,P18433-2,4.476120e+05,NaN,NaN,NaN,NaN,NaN
4,4,PKCD,PTPRA iso2,human,human,QAGSHSNSFRLSNGR,S180,Q05655,5786.0,P18433-2,1.869334e+09,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14279,14279,ULK2,Raptor,human,human,DTSSLTQSAPASPTN,S859,Q8IYT8,57521.0,Q8N122,2.024885e+06,NaN,NaN,NaN,NaN,NaN
14280,14280,ULK2,DENND3,human,human,ELAPRNSSLRLTDTA,S490,Q8IYT8,22898.0,A2RUS2,2.305019e+07,NaN,NaN,NaN,NaN,NaN
14281,14281,ULK2,DENND3,human,human,THRRMVVSMPNLQDI,S472,Q8IYT8,22898.0,A2RUS2,7.997148e+06,NaN,NaN,NaN,NaN,NaN
14282,14282,ULK2,SEC16A,human,human,LAQPINFSVSLSNSH,S846,Q8IYT8,9919.0,O15027,5.557872e+07,NaN,NaN,NaN,NaN,NaN
14283,14283,ULK2,PIK3C3,human,human,ESSPILTSFELVKVP,S249,Q8IYT8,5289.0,Q8NEB9,3.548321e+07,NaN,NaN,NaN,NaN,NaN

In [13]:
df_freq = df[['KINASE_psp', 'KIN_ACC_ID_psp', 'SUBSTRATE_psp']]
df_freq

      KINASE_psp KIN_ACC_ID_psp SUBSTRATE_psp
0            HRI         Q9BQI3    eIF2-alpha
1            HRI         Q9BQI3    eIF2-alpha
2           PKCD         Q05655         HDAC5
3           PKCD         Q05655    PTPRA iso2
4           PKCD         Q05655    PTPRA iso2
...          ...            ...           ...
14279       ULK2         Q8IYT8        Raptor
14280       ULK2         Q8IYT8        DENND3
14281       ULK2         Q8IYT8        DENND3
14282       ULK2         Q8IYT8        SEC16A
14283       ULK2         Q8IYT8        PIK3C3

[14284 rows x 3 columns]

In [14]:
df_freq.groupby(['KINASE_psp', 'KIN_ACC_ID_psp']).size().reset_index(name='Frequency_SUBSTRATE_psp').sort_values(by='Frequency_SUBSTRATE_psp', ascending=False).to_csv('../data/frequency_substrate_ranked_1.csv', index=False)

In [15]:
grouped = df_freq.groupby(['KINASE_psp', 'KIN_ACC_ID_psp'])

In [16]:
# groupby first two column and then apply lambda function to get the unique substrates
grouped['SUBSTRATE_psp'].unique().reset_index(name='Unique_SUBSTRATE_psp')

,KINASE_psp,KIN_ACC_ID_psp,Unique_SUBSTRATE_psp
0,AAK1,Q2M2I8,"[AP2M1, NUMB]"
1,ADCK5,Q3MIX3,[SOX9]
2,ALK,Q9UM73,"[ALK, ELP3, PSF, ATIC, STAT3, SHP-2, SNIP iso5..."
3,ALK1,P37023,[ENG]
4,ALK4,P36896,[TTRAP]
...,...,...,...
411,p70S6K,P23443,"[BACH2, IRS1, NDRG2, KHSRP, PDCD4, p63, mTOR, ..."
412,p70S6K iso2,P23443-2,"[GSK3B, EPRS]"
413,p90RSK,Q15418,"[TERF2IP, AS160, NHE1, KIBRA, NDRG2, VASP, CDC..."
414,skMLCK,Q9H1R3,[MEF2C]
415,smMLCK,Q15746,"[MRLC2V, MRLC1, MRLC2]"

In [17]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
import pickle

In [18]:
rank='2'

In [19]:
df = pd.read_csv(f'../data/cleaned_ranked_{rank}.csv')
df

,Unnamed: 0,KINASE_psp,SUBSTRATE_psp,KIN_ORGANISM_psp,SUB_ORGANISM_psp,SITE_+/-7_AA_psp,SUB_MOD_RSD_psp,KIN_ACC_ID_psp,SUB_GENE_ID_psp,SUB_ACC_ID_psp,SITE_GRP_ID_psp,Uniprot Primary Accession_johnson,Protein_johnson,Phosphosite_johnson,SITE_+/-7_AA_johnson,ranked_2_johnson
0,0,HRI,eIF2-alpha,human,human,MILLSELSRRRIRSI,S52,Q9BQI3,1965.0,P05198,4.476350e+05,NaN,NaN,NaN,NaN,NaN
1,1,HRI,eIF2-alpha,human,human,IEGMILLSELSRRRI,S49,Q9BQI3,1965.0,P05198,4.502100e+05,NaN,NaN,NaN,NaN,NaN
2,2,PKCD,HDAC5,human,human,FPLRKTASEPNLKVR,S259,Q05655,10014.0,Q9UQL6,4.479950e+05,NaN,NaN,NaN,NaN,NaN
3,3,PKCD,PTPRA iso2,human,human,PLLARSPSTNRKYPP,S204,Q05655,5786.0,P18433-2,4.476120e+05,NaN,NaN,NaN,NaN,NaN
4,4,PKCD,PTPRA iso2,human,human,QAGSHSNSFRLSNGR,S180,Q05655,5786.0,P18433-2,1.869334e+09,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14138,14138,ULK2,Raptor,human,human,DTSSLTQSAPASPTN,S859,Q8IYT8,57521.0,Q8N122,2.024885e+06,NaN,NaN,NaN,NaN,NaN
14139,14139,ULK2,DENND3,human,human,ELAPRNSSLRLTDTA,S490,Q8IYT8,22898.0,A2RUS2,2.305019e+07,NaN,NaN,NaN,NaN,NaN
14140,14140,ULK2,DENND3,human,human,THRRMVVSMPNLQDI,S472,Q8IYT8,22898.0,A2RUS2,7.997148e+06,NaN,NaN,NaN,NaN,NaN
14141,14141,ULK2,SEC16A,human,human,LAQPINFSVSLSNSH,S846,Q8IYT8,9919.0,O15027,5.557872e+07,NaN,NaN,NaN,NaN,NaN
14142,14142,ULK2,PIK3C3,human,human,ESSPILTSFELVKVP,S249,Q8IYT8,5289.0,Q8NEB9,3.548321e+07,NaN,NaN,NaN,NaN,NaN

In [20]:
len(df)

14143

In [21]:
# show all rows 
# pd.set_option('display.max_rows', None)

In [22]:
df['length_of_sequence'] = df['SITE_+/-7_AA_psp'].apply(lambda x: len(x))
df

,Unnamed: 0,KINASE_psp,SUBSTRATE_psp,KIN_ORGANISM_psp,SUB_ORGANISM_psp,SITE_+/-7_AA_psp,SUB_MOD_RSD_psp,KIN_ACC_ID_psp,SUB_GENE_ID_psp,SUB_ACC_ID_psp,SITE_GRP_ID_psp,Uniprot Primary Accession_johnson,Protein_johnson,Phosphosite_johnson,SITE_+/-7_AA_johnson,ranked_2_johnson,length_of_sequence
0,0,HRI,eIF2-alpha,human,human,MILLSELSRRRIRSI,S52,Q9BQI3,1965.0,P05198,4.476350e+05,NaN,NaN,NaN,NaN,NaN,15
1,1,HRI,eIF2-alpha,human,human,IEGMILLSELSRRRI,S49,Q9BQI3,1965.0,P05198,4.502100e+05,NaN,NaN,NaN,NaN,NaN,15
2,2,PKCD,HDAC5,human,human,FPLRKTASEPNLKVR,S259,Q05655,10014.0,Q9UQL6,4.479950e+05,NaN,NaN,NaN,NaN,NaN,15
3,3,PKCD,PTPRA iso2,human,human,PLLARSPSTNRKYPP,S204,Q05655,5786.0,P18433-2,4.476120e+05,NaN,NaN,NaN,NaN,NaN,15
4,4,PKCD,PTPRA iso2,human,human,QAGSHSNSFRLSNGR,S180,Q05655,5786.0,P18433-2,1.869334e+09,NaN,NaN,NaN,NaN,NaN,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14138,14138,ULK2,Raptor,human,human,DTSSLTQSAPASPTN,S859,Q8IYT8,57521.0,Q8N122,2.024885e+06,NaN,NaN,NaN,NaN,NaN,15
14139,14139,ULK2,DENND3,human,human,ELAPRNSSLRLTDTA,S490,Q8IYT8,22898.0,A2RUS2,2.305019e+07,NaN,NaN,NaN,NaN,NaN,15
14140,14140,ULK2,DENND3,human,human,THRRMVVSMPNLQDI,S472,Q8IYT8,22898.0,A2RUS2,7.997148e+06,NaN,NaN,NaN,NaN,NaN,15
14141,14141,ULK2,SEC16A,human,human,LAQPINFSVSLSNSH,S846,Q8IYT8,9919.0,O15027,5.557872e+07,NaN,NaN,NaN,NaN,NaN,15
14142,14142,ULK2,PIK3C3,human,human,ESSPILTSFELVKVP,S249,Q8IYT8,5289.0,Q8NEB9,3.548321e+07,NaN,NaN,NaN,NaN,NaN,15

In [23]:
df = df[~df['SITE_+/-7_AA_psp'].apply(lambda x: '_' in x)]

In [24]:
df['length_of_sequence'].value_counts()

15    13644
Name: length_of_sequence, dtype: int64

In [25]:
df[['KINASE_psp', 'SITE_+/-7_AA_psp']].head()

  KINASE_psp SITE_+/-7_AA_psp
0        HRI  MILLSELSRRRIRSI
1        HRI  IEGMILLSELSRRRI
2       PKCD  FPLRKTASEPNLKVR
3       PKCD  PLLARSPSTNRKYPP
4       PKCD  QAGSHSNSFRLSNGR

In [26]:
df['KINASE_psp'].nunique()

407

In [27]:
# !pip install logomaker

In [28]:
df.groupby('KINASE_psp')['SITE_+/-7_AA_psp'].apply(list)

KINASE_psp
AAK1                          [SQITSQVTGQIGWRR, LRVVDEKTKDLIVDQ]
ADCK5                                          [YQPRRRKSVKNGQAE]
ALK            [TAPGAGHYEDTILKS, FGMARDIYRASYYRK, GHTSNNIYEAV...
ALK1           [STNHSIGSTQSTPCS, ASSESSSTNHSIGST, HSIGSTQSTPC...
ALK4                          [PKTYVDLTNEETTDS, VDLTNEETTDSTTSK]
                                     ...
p70S6K         [ETRTRTSSSCSSYSY, SGDYMPMSPKSVSAP, TRRSRTESITA...
p70S6K iso2                   [SGRPRTTSFAESCKP, NQGGGLSSSGAGEGQ]
p90RSK         [GDAPVSPSSQKLKRK, EFRSRCSSVTGVQRR, AKRSLTSSLEN...
skMLCK                                         [NEPHESRTNSDIVET]
smMLCK         [KRAGGANSNVFSMFE, KKRPQRATSNVFAMF, KRPQRATSNVF...
Name: SITE_+/-7_AA_psp, Length: 407, dtype: object

In [29]:
f.groupby('KINASE_psp')['SITE_+/-7_AA_psp'].apply(list).to_csv('psp_freq_matrix.csv')

NameError: name 'f' is not defined

In [ ]:
df.columns

In [ ]:
df.groupby(f'ranked_{rank}_johnson')['SITE_+/-7_AA_johnson'].apply(list)

In [ ]:
df.groupby(f'ranked_{rank}_johnson')['SITE_+/-7_AA_johnson'].apply(list).to_csv('johnson_freq_matrix.csv')

In [ ]:
create_pssm(df, 'KINASE_psp', 'SITE_+/-7_AA_psp', 'psp_pssm.pkl')

In [ ]:
create_pssm(df, f'ranked_{rank}_johnson', 'SITE_+/-7_AA_johnson', 'johnson_pssm.pkl')

In [ ]:
# import logomaker
# from collections import Counter

# # Group by 'KINASE_psp' and combine all sequences into a list
# kinase_sequences = df.groupby('KINASE_psp')['SITE_+/-7_AA_psp'].apply(list)

# # Initialize an empty dictionary to store the Logos for each kinase
# kinase_logos = {}

# # For each kinase, create a position frequency matrix and then a sequence logo
# for kinase, sequences in kinase_sequences.items():
#     # Combine sequences into a single string for each position
#     aligned_sequences = [''.join(seq) for seq in zip(*sequences)]
    
#     # Create a DataFrame where each row corresponds to one position
#     position_df = pd.DataFrame([Counter(pos) for pos in aligned_sequences]).fillna(0)
    
#     # Normalize the counts to get frequencies
#     position_freq_matrix = position_df.div(position_df.sum(axis=0), axis=1)
    
#     # Create the sequence logo
#     logo = logomaker.Logo(position_freq_matrix, color_scheme='skylign_protein', stack_order='small_on_top')
    
#     # Set title and axis labels
#     logo.ax.set_title(f'Sequence Logo for {kinase}')
#     logo.ax.set_xlabel('Position')
#     logo.ax.set_ylabel('Frequency')
    
#     # Store the logo in the dictionary
#     kinase_logos[kinase] = logo

In [ ]:
import pandas as pd 
import pickle 

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# load pickled data
with open('psp_pssm.pkl', 'rb') as f:
    PSSM_PSP = pickle.load(f)

In [ ]:
PSSM_PSP.keys()

In [ ]:
with open('johnson_pssm.pkl', 'rb') as f:
    PSSM_johnson = pickle.load(f)

In [ ]:
PSSM_johnson.keys()

In [ ]:
common_family = set(PSSM_PSP.keys()).intersection(set(PSSM_johnson.keys()))

In [ ]:
common_family

In [ ]:
family = list(common_family)[0]

In [ ]:
len(PSSM_PSP.keys())

In [ ]:
len(PSSM_PSP[family].columns)

In [ ]:
PSSM_PSP.keys()

In [ ]:
family = list(common_family)[0]
family

In [ ]:
PSSM_PSP[family].head()

In [ ]:
PSSM_johnson[family].head()

In [ ]:
PSSM_PSP[family].columns

In [ ]:
len(PSSM_PSP[family].columns), len(PSSM_johnson[family].columns)

In [ ]:
PSSM_PSP[family].shape[1]

In [ ]:
PSSM_johnson[family].columns

In [ ]:
for family in common_family:
    pssm1 = PSSM_PSP[family]
    pssm2 = PSSM_johnson[family]

    if pssm1.shape[1] != pssm2.shape[1]:
        print(family, 'PSP and Johson data have different lengths')
        print(f"Psp is {pssm1.shape[1]} and Johnson is {pssm2.shape[1]}")
        print(f"psp columns: {pssm1.columns} and johnson columns: {pssm2.columns}")
        print("----------------------------------------")
        continue

    # make the columns match
    try:
        print("***********")
        print(f"{family} is being processed")
        pssm1 = pssm1[pssm2.columns]
    
        # Calculate Euclidean distances for each position
        distances = np.linalg.norm(pssm1 - pssm2, axis=1)

        # Plotting the PSSMs and distances
        fig, axes = plt.subplots(1, 3, figsize=(15, 5))
        # set figure title 
        fig.suptitle(family)

        sns.heatmap(pssm1, ax=axes[0], cmap='viridis', cbar=False)
        axes[0].set_title('Psp')

        sns.heatmap(pssm2, ax=axes[1], cmap='viridis', cbar=False)
        axes[1].set_title('Johnson')

        axes[2].plot(distances, marker='o')
        axes[2].set_title('Euclidean Distance per Position')
        axes[2].set_xlabel('Position')
        axes[2].set_ylabel('Euclidean Distance')

        plt.tight_layout()
        plt.show()
    except Exception as e:
        print(family, e)